version: '3.1'

services:

  pinger:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db
    environment:
      - PG_USER
      - PG_PASS
      - DB_URL

  db:
    image: postgres
    environment:
      POSTGRES_DB: pinger
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER}
    ports:
      - 5432:5432